In [ ]:






#Numpy is a Python library created to work with arrays. 
#The numpy library also has functions for performing various operations on linear algebra, Fourier transform, and matrices.
#Numpy was created in 2005 by Travis Oliphant as an open source project.
#Numpy The numerical Python stands for Numerical Python.

In [ ]:
#Installation Method
#Go to Google Coolb
#And the phrase! Pip install numpy Write

In [ ]:
#Reminiscent of Python
list = [1,2,3,4]
print(list)
print(type(list))

[1, 2, 3, 4]
<class 'list'>


In [ ]:
#Array in Python
import numpy as np
array = np.array([1,2,3,4,5])
print(array)
print(type(array))



[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#array of presentation with list
import numpy as np
array = np.array([1,2,3,4,5])
print(array[1])
print(array[1:3])
print(array[:-1])
#It's a lot like a list isn't it?


2
[2 3]
[1 2 3 4]


In [ ]:
#Change elements in array
import numpy as np
array = np.array([1,2,3,4,5])
array[2] = 87
print(array)
#very good

[ 1  2 87  4  5]


In [ ]:
#2D array
import numpy as np
array_2d = np.array([[1,2,3],
                     [4,4,6],
                     [7,8,9]
                     ])
print(array_2d)
print("-------")
print(array_2d[0])
print("-------")
print(array_2d[1])
print("-------")
print(array_2d[2])
print("-------")
print(array[1:2])
#Like the matrix that i and j have With the difference that i and j start from zero




[[1 2 3]
 [4 4 6]
 [7 8 9]]
-------
[1 2 3]
-------
[4 4 6]
-------
[7 8 9]
-------
[2]


In [ ]:
import numpy as np
array_2d = np.array([[1,2,3],
                     [4,4,6],
                     [7,8,9]

                     ])
#Shows rows and columns
print(array_2d.shape)
#Number of array dimensions.
print(array_2d.ndim)
#Indicates the number of elements
print(array_2d.size)
#Indicates the type
print(array_2d.dtype)

(3, 3)
2
9
int64


In [ ]:
#filling array

import numpy as np
array = np.full((3,4), 5)
#It has 3 arguments
#The first argument is row
#The second  argument is column
#The third argument is the number you want to put
print(array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
import numpy as np
#All elements are zero
array_z = np.zeros((3,4))
print(array_z)
#It has 2 arguments
#The first argument is row
#The second  argument is column

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import numpy as np
#All elements are one
array_one = np.ones((3,4))
print(array_one)
#It has 2 arguments
#The first argument is row
#The second  argument is column

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np
#Takes any amount from memory
array_empty = np.empty((3,5))
print(array_empty)
#It has 2 arguments
#The first argument is row
#The second  argument is column


[[4.68105517e-310 1.06099790e-312 1.01855798e-312 9.54898106e-313
  1.16709769e-312]
 [1.03977794e-312 1.23075756e-312 1.16709769e-312 1.06099790e-312
  9.76118064e-313]
 [1.03977794e-312 1.12465777e-312 1.18831764e-312 4.44659081e-322
  0.00000000e+000]]


In [ ]:
#Build a sequence
import numpy as np

sequence = np.arange(0,1000,5)
#It has 3 arguments
##The first argument is row
#The second  argument is column
#The third argument is Step
#Note that the third argument means the end and is not printed by itself

print(sequence)


[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [ ]:
import numpy as np
linspace = np.linspace(0,10,5)
#It has 3 arguments
##The first argument is row
#The second  argument is column
#The third argument is Step
print(linspace)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
import numpy as np

print(np.nan)
print(np.inf)

nan
inf


In [ ]:
import numpy as np

l1 = [1,2,3,4,5,6]
ar = np.array(l1)
print(l1 * 3)
#There you have to multiply a list by three
#Prints it three times in a row
#Math operations not defined in the list


#and see that
print(ar* 3)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
[ 3  6  9 12 15 18]


In [ ]:
import numpy as np

l1 = [1,2,3,4,5,6]
ar = np.array(l1)
print(ar + 4)
#See all elements plus zero


#Run this and see the result
#print(l1 + 3)


#Saw the error   See the sum of the two lists
print(l1 + l1) # print(l1 * 2)

[ 5  6  7  8  9 10]
[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [ ]:
#Mathematical property gives addition and subtraction, division of numbers, and even two error lists
#Try it for yourself


In [ ]:
import numpy as np

l1 = [1,2,3,4,5,6]
ar1 = np.array(l1)

l2 = [10,10,10,10,10,10]
ar2 = np.array(l2)

print(ar1 * ar2)
#Mathematical operations are performed side by side
print(ar1 * ar2)
print(ar1 / ar2)
print(ar1 + ar2)
print(ar1 - ar2)

[10 20 30 40 50 60]
[10 20 30 40 50 60]
[0.1 0.2 0.3 0.4 0.5 0.6]
[11 12 13 14 15 16]
[-9 -8 -7 -6 -5 -4]


In [ ]:
import numpy as np


ar1 = np.array([1,2,3])
ar2 = np.array([[1],
               [2]
               ])


print(ar1 + ar2)

#So cool
#Once the presentation is assembled with the first row
#And the second time with the second row

#****Matrix addition rules are not here. Make no mistake


[[2 3 4]
 [3 4 5]]


In [ ]:
#Let's look at mathematical methods
import numpy as np

ar1 = np.array([[1,2,3],
                [4,5,6]
               ])


print(np.sqrt(ar1))
print("-----------------------------------")

print(np.sin(ar1))
print("-----------------------------------")

print(np.cos(ar1))
print("-----------------------------------")

print(np.tan(ar1))
print("-----------------------------------")

print(np.arctan(ar1))
print("-----------------------------------")

print(np.exp(ar1))
print("-----------------------------------")

print(np.log10(ar1))
print("-----------------------------------")

print(np.log2(ar1))
print("-----------------------------------")



[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
-----------------------------------
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
-----------------------------------
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
-----------------------------------
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
-----------------------------------
[[0.78539816 1.10714872 1.24904577]
 [1.32581766 1.37340077 1.40564765]]
-----------------------------------
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
-----------------------------------
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
-----------------------------------
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]]
-----------------------------------


In [ ]:
from numpy.lib.function_base import append
#array method
ar = np.array([1,2,3])
#add
ar = append(ar, [3,4,5])
#You do not need a bracket for a variable
print(ar)


[1 2 3 3 4 5]


In [ ]:
import numpy as np
ar = np.array([[1,2,3],
               [4,5,6]
               ])
 
ar = np.delete(ar , 1)
#Removes by vector
print(ar) 

[1 3 4 5 6]


In [ ]:
import numpy as np
ar = np.array([[1,2,3],
               [4,5,6]
               ])
ar = np.delete(ar , 0, 1)
#Cleans in a way that does not distort its shape
print(ar)


[[2 3]
 [5 6]]


In [ ]:
import numpy as np
ar = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])
print(ar.shape)
ar = ar.reshape(5,4)
print(ar)
print("------------------")

ar = ar.reshape(1,20)
print(ar)
print("------------------")
ar = ar.reshape(20,1)
print(ar)

(4, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
------------------
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]
------------------
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]


In [ ]:
import numpy as np
ar = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])

ar.resize((10,2))
print(ar)
print("--------------------")
ar = ar.reshape(10,2)
print(ar)
#The only difference with the previous method is that it saves directly and does not need to be returned to itself.

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
--------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [ ]:
#Flattening
import numpy as np
ar = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])



ar = ar.flatten()
print(ar)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#Flattening
import numpy as np
ar = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])

l1 = ar.flatten()
l1[2] = 10000
print(l1)
print(ar)
print("----------------")

l2 = ar.ravel()
l2[2] = 10000
print(l2)
print(ar)
#You see, ravel() is a copy function for the original array

[    1     2 10000     4     5     6     7     8     9    10    11    12
    13    14    15    16    17    18    19    20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
----------------
[    1     2 10000     4     5     6     7     8     9    10    11    12
    13    14    15    16    17    18    19    20]
[[    1     2 10000     4     5]
 [    6     7     8     9    10]
 [   11    12    13    14    15]
 [   16    17    18    19    20]]


In [ ]:
#Flattening
import numpy as np
ar = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])


var = [v for v in ar.flat]
print(var)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [ ]:
#Rotation
import numpy as np
ar = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])


print(ar.transpose()) 
print(ar.T)
#This is a spin that you notice by looking

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [ ]:
#Aggregate Functions
import numpy as np
ar = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])

#Shows the lowest membership
print(ar.min())
#Shows the largest member
print(ar.max())
#Shows the average
print(ar.mean())
#Indicates standard deviation
print(ar.std())
#Shows the sum of all elements
print(ar.sum())
#Shows the middle
print(np.median(ar))

1
20
10.5
5.766281297335398
210
10.5


In [ ]:
#random
import numpy as np
number = np.random.randint(100)
#randint-->Integer
#100-->Range 100
print(number)

29


In [ ]:
#random
import numpy as np
array = np.random.randint(100, size = (4,5))
#array 4 X 5
print(array)

[[26  0 41 50 44]
 [33 31 91 92 15]
 [38  8 97 50 18]
 [95 53 46 74  9]]


In [ ]:
#random
import numpy as np
array = np.random.randint(80 ,100, size = (4,5))
#array 4 X 5
print(array)
#range 80 --- > 99

[[84 97 81 80 97]
 [86 87 98 89 90]
 [91 83 84 88 82]
 [84 92 96 93 83]]


In [ ]:
#random
import numpy as np
numbers = np.random.binomial(10, p = 0.4 , size = (4,4))
#p --> Possibility
print(numbers)

[[5 7 4 7]
 [3 5 2 5]
 [5 5 3 5]
 [4 3 6 3]]


In [ ]:
#random
import numpy as np
number = np.random.choice([10,25,368,145,48])
print(number)
print("--------------------")
number = np.random.choice([10,25,368,145,48], size = (4,5))
print(number)

145
--------------------
[[ 48  25  25  25 145]
 [368  10 145  48  48]
 [ 48 145 368  48 368]
 [ 48  48 368  10  48]]


In [ ]:
#csv files
import numpy as np
ar = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])


np.save("1.npy", ar)
#If you see the file Is binary
files = np.load("1.npy")
print(files)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
#csv files
import numpy as np
ar = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])

np.savetxt("2.csv", ar, delimiter  = ",")
files = np.loadtxt("2.csv", delimiter  = ",")
print(files)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


In [ ]:
#matrix
import numpy as np

m = np.matrix([[1,2],[3,4]])
print(m)

[[1 2]
 [3 4]]


In [ ]:
#matrix
import numpy as np

m = np.matrix([[1,2],[3,4]])
print(np.linalg.inv(m))
#Inverse Matrix

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#matrix
import numpy as np

m1 = np.matrix([[1,2],[3,4]])
print(m1)

m2 = np.matrix([[1],[2]])
print(m2)

print(np.linalg.inv(m1).dot(m2))
#(Inverse Matrix m1) * (m2)

[[1 2]
 [3 4]]
[[1]
 [2]]
[[0. ]
 [0.5]]


In [ ]:
#matrix
import numpy as np
m1 = np.matrix([[1,2],[3,4]])
print(m1)

m2 = np.matrix([[1],[2]])
print(m2)

print(np.linalg.solve(m1,m2))
#It looked like a top

[[1 2]
 [3 4]]
[[1]
 [2]]
[[0. ]
 [0.5]]
